-- ============================================================
-- FitFlow Manager — Schema completo do banco de dados
-- PostgreSQL, com ON DELETE CASCADE em todas as FKs
-- ============================================================

DROP TABLE IF EXISTS item_realizado       CASCADE;
DROP TABLE IF EXISTS serie_treino         CASCADE;
DROP TABLE IF EXISTS sessao_treino        CASCADE;
DROP TABLE IF EXISTS item_treino          CASCADE;
DROP TABLE IF EXISTS programacao_treino   CASCADE;
DROP TABLE IF EXISTS avaliacao_fisica     CASCADE;
DROP TABLE IF EXISTS comentario_treino    CASCADE;
DROP TABLE IF EXISTS exercicio            CASCADE;
DROP TABLE IF EXISTS treino               CASCADE;
DROP TABLE IF EXISTS objetivo             CASCADE;
DROP TABLE IF EXISTS aluno                CASCADE;
DROP TABLE IF EXISTS instrutor            CASCADE;
DROP TABLE IF EXISTS admin                CASCADE;
DROP TABLE IF EXISTS usuario              CASCADE;

-- ============================================================
-- Herança JOINED: usuario → {admin, instrutor, aluno}
-- ============================================================

CREATE TABLE usuario (
    id       SERIAL       NOT NULL,
    nome     VARCHAR(255) NOT NULL,
    email    VARCHAR(255),
    cpf      VARCHAR(255),
    senha    VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE admin (
    id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES usuario(id) ON DELETE CASCADE
);

CREATE TABLE instrutor (
    id    INT          NOT NULL,
    cref  VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES usuario(id) ON DELETE CASCADE
);

CREATE TABLE aluno (
    id      INT   NOT NULL,
    peso    REAL,
    altura  REAL,
    imc     REAL,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES usuario(id) ON DELETE CASCADE
);

-- ============================================================
-- Avaliação física do aluno
-- ============================================================

CREATE TABLE avaliacao_fisica (
    id              BIGSERIAL NOT NULL,
    aluno_id        INT       NOT NULL,
    peso            REAL,
    altura          REAL,
    imc             REAL,
    data_avaliacao  DATE,
    PRIMARY KEY (id),
    FOREIGN KEY (aluno_id) REFERENCES aluno(id) ON DELETE CASCADE
);

-- ============================================================
-- Exercício e Treino
-- ============================================================

CREATE TABLE objetivo (
    id    INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome  VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE treino (
    id            INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR(255),
    objetivo_id   INT,
    ficha_padrao  BOOLEAN,
    PRIMARY KEY (id),
    FOREIGN KEY (objetivo_id) REFERENCES objetivo(id) ON DELETE SET NULL
);

CREATE TABLE exercicio (
    id             INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome           VARCHAR(255),
    grupo_muscular VARCHAR(255),
    descricao      VARCHAR(255),
    url_midia      VARCHAR(255),
    PRIMARY KEY (id)
);

-- ============================================================
-- Item de treino (um exercício dentro de um treino)
-- ============================================================

CREATE TABLE item_treino (
    id                 INT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    intervalo_descanso REAL,
    progressao_carga   BOOLEAN,
    treino_id          INT,
    exercicio_id       INT,
    PRIMARY KEY (id),
    FOREIGN KEY (treino_id)    REFERENCES treino(id)    ON DELETE CASCADE,
    FOREIGN KEY (exercicio_id) REFERENCES exercicio(id) ON DELETE CASCADE
);

-- ============================================================
-- Séries de um item de treino
-- ============================================================

CREATE TABLE serie_treino (
    id              INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    numero_da_serie INT,
    repeticoes      INT,
    carga           REAL,
    item_treino_id  INT,
    PRIMARY KEY (id),
    FOREIGN KEY (item_treino_id) REFERENCES item_treino(id) ON DELETE CASCADE
);

-- ============================================================
-- Programação de treino (ficha ativa do aluno)
-- ============================================================

CREATE TABLE programacao_treino (
    id                  INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    data_inicio_semanas TIMESTAMP,
    data_fim_semanas    TIMESTAMP,
    dia_da_semana       VARCHAR(255),
    aluno_id            INT,
    treino_id           INT,
    PRIMARY KEY (id),
    FOREIGN KEY (aluno_id)  REFERENCES aluno(id)  ON DELETE CASCADE,
    FOREIGN KEY (treino_id) REFERENCES treino(id) ON DELETE CASCADE
);

-- ============================================================
-- Sessão de treino (execução de uma ficha pelo aluno)
-- ============================================================

CREATE TABLE sessao_treino (
    id                     INT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    data                   TIMESTAMP,
    concluido              BOOLEAN,
    programacao_treino_id  INT,
    PRIMARY KEY (id),
    FOREIGN KEY (programacao_treino_id) REFERENCES programacao_treino(id) ON DELETE CASCADE
);

-- ============================================================
-- Item realizado (exercício executado dentro de uma sessão)
-- ============================================================

CREATE TABLE item_realizado (
    id                       INT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    carga_utilizada          REAL,
    feito                    BOOLEAN,
    sessao_treino_id         INT,
    item_treino_id           INT,
    tempo_descanso_segundos  INT,
    tempo_execucao_segundos  INT,
    status_carga             VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (sessao_treino_id) REFERENCES sessao_treino(id) ON DELETE CASCADE,
    FOREIGN KEY (item_treino_id)   REFERENCES item_treino(id)  ON DELETE CASCADE
);

-- ============================================================
-- Comentário / feedback do aluno sobre um treino
-- ============================================================

CREATE TABLE comentario_treino (
    id           INT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    aluno_id     INT,
    treino_id    INT,
    texto        VARCHAR(255),
    data_criacao TIMESTAMP,
    lido         BOOLEAN,
    PRIMARY KEY (id),
    FOREIGN KEY (aluno_id)  REFERENCES aluno(id)  ON DELETE CASCADE,
    FOREIGN KEY (treino_id) REFERENCES treino(id) ON DELETE CASCADE
);

-- ============================================================
-- Seed: objetivos padrão
-- ============================================================

INSERT INTO objetivo (nome) VALUES
    ('Hipertrofia'),
    ('Emagrecimento'),
    ('Condicionamento'),
    ('Força Pura'),
    ('Reabilitação'),
    ('Manutenção'),
    ('Saúde Geral');
